server:
  port: 8081
  context-path: /bookmanage
spring:
  datasource:
    url: jdbc:mysql://liuhaihua.top:3306/mybatis?characterEncoding=UTF8
    username: mybatis
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 3
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    database: 0
    host: 66.42.39.63
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#mybatis:
#  typeAliasesPackage: com.limai.entity
#  mapperLocations: classpath:mapper/*.xml

#配置logback日志功能
logging:
  config: classpath:config/logback-boot.xml

 #配置超级管理员
bookmanage:
  role:
    admin:
      - 13659289075
      - 18234132264
      - 17600903045
      - 15910504070
      - 15901233060
      - 18210815033
      - 15201218131
    headman:
      - 13659289075

limai:
  dingding:
    employeeUrl: http://usercenter.vipsdb.com/employees/login
    allEmployeesUrl: http://usercenter.vipsdb.com/employees
    allDeptsUrl: http://usercenter.vipsdb.com/departments
